# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 814ecbb191a7a18703694a196132da2b049db12f1201746cc5fd803f981cdf685547f959215e71670e4de3197e7ba719bf7ddfb6214548baa8956a08c88e98bc


test:
  secret_key_base: f933929aac10b5e47e3dc37f8667f1bc55b9958ba26ebc4cd0019b235435711c7c1ae95fd50a9c0b07c7c8da65d3c81ca471a23c485a0567453a41bb3e903928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


